### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by slorber** [pomber/stargazer#11]
I get this error when trying to run the action with "facebook/docusaurus" and getting failures

https://github.com/slorber/stargazer/actions
https://github.com/slorber/stargazer/actions/runs/3655732936/jobs/6177475539

<img width="1742" alt="CleanShot 2022-12-09 at 09 46 13@2x" src="https://user-images.githubusercontent.com/749374/206661761-e78abfb7-e4d0-4943-9bdc-7abb674d3ed4.png">

(the successful runs are using your default repo action settings)

**Comment by JonnyBurger** [comment]
👋 Just became a co-maintainer of the repo!

Improved retries on rate limit, caching, error handling, and upgraded to Remotion 4.0's new data fetching!
It now runs fine on Docusaurus' massive star crowd.

Here is a video for 45k: https://github.com/JonnyBurger/stargazer/actions/runs/5321287440
