### ISSUE TITLE
For Forked repo also.

### ISSUE THREAD

**Issue by Darsh0307** [pomber/stargazer#19]
Hello 

It will be really good if we can make video of same kind for all the forked branches also ?

**Comment by JonnyBurger** [comment]
Is there something preventing you from entering a fork?

**Comment by hrittikhere** [comment]
Hey @JonnyBurger 
Loved this repository and awesome work. Mind adding a License to the repository? :)

**Comment by JonnyBurger** [comment]
@pomber Would it be okay to add this at the bottom of the README?

> The code in this repository: Licensed under MIT.  
> The Remotion framework (a dependency of this project): Normally, companies need to obtain a [paid license](https://github.com/remotion-dev/remotion/blob/main/LICENSE.md#company-license).  
> However, it is accepted to create videos off this template without needing a company license.

**Comment by pomber** [comment]
> @pomber Would it be okay to add this at the bottom of the README?
> 
> > The code in this repository: Licensed under MIT.
> > The Remotion framework (a dependency of this project): Normally, companies need to obtain a [paid license](https://github.com/remotion-dev/remotion/blob/main/LICENSE.md#company-license).
> > However, it is accepted to create videos off this template without needing a company license.

[Done!](https://github.com/pomber/stargazer/commit/7b5225177aeba0a24d908fa1b4961ec51ae7e08d)

**Comment by JonnyBurger** [comment]
Thanks!
