### ISSUE TITLE
Visual glitches after a lot of stars

### ISSUE THREAD

**Issue by mrousavy** [pomber/stargazer#5]
I'm trying to render a star overview for react-native-vision-camera, but it seems like some stargazers get stuck and it looks like a visual glitch... see this video:

https://user-images.githubusercontent.com/15199031/131339205-566b9015-fca0-4dd0-bab1-e5b8cacde316.mp4

Config: 
* org: mrousavy
* repo: react-native-vision-camera
* stars: 1458
* duration: 15 sec

**Comment by skeltsyboiii** [comment]
@mrousavy did you end up finding a solve for this?

**Comment by JonnyBurger** [comment]
Hey Marc, just became co-maintainer of the repo!
Looks like the bug is due to two stargazers having the same display name, causing a React duplicate key error.

Fixing in #13!

**Comment by JonnyBurger** [comment]
Here is your video:


https://github.com/pomber/stargazer/assets/1629785/e5ea7c97-2863-4207-a4e4-9c469905fb30
